mode:                              'profiler'

maplab_server_prefix:              '/maplab_server/maplab_server_node/'
maplab_server_reinit_sevice:       '/maplab_server/reinit_gflags'
maplab_reset_global_map:           '/maplab_server/delete_all_robot_missions'

init_profile:                      'default'
config_root:                       '/home/berlukas/Documents/workspace/darpa/src/darpa_subt_mapping/maplab/dependencies/internal/maplab_tools/maplab_profiles/config/'
profiles:
  - 'default'
  - 'high_performance'
  - 'low_performance'
  - 'lidar-only'

# Profiler configs
##################
profiling_submap_folder:           '/home/berlukas/Documents/results/hagerbach_july/'
profiling_send_n_submaps:          1
profiling_robots:
  - 'mission_05_anymal_5'
profiling_mode:                    parallel
profiling_delays:
  - 0
profiling_rate:                    0.1
profiling_completion_sleep_time_s: 20
profiling_merged_map_path:         '/tmp/maplab_server/merged_map/'
profiling_ground_truth_path:       '/home/berlukas/Documents/results/hagerbach_july/mission_05_opt/'
profiling_grid_search_params_file: 'debug_grid_search'
